import 'package:coffeeapp/model/category.dart';
import 'package:coffeeapp/model/drinkItem.dart';

final List<Categorys> menu = [
  Categorys(
    name: "Iced Coffee",
    items: [
      Drinkitem(
        title: "Iced Americano",
        description: "Rich espresso with chilled water.",
        img: "assets/drinks/ice/iced_americano.png",
        sPrice: 2.00,
        lPrice: 2.50,
        sugarLevels: [0, 25, 50, 75, 100],
        iceOptions: ["Less Ice", "Normal", "Separate"],
        hasCoffee: true,
      ),
      Drinkitem(
        title: "Iced Latte",
        description: "Espresso with fresh milk.",
        img: "assets/drinks/ice/iced_latte.png",
        sPrice: 2.75,
        lPrice: 3.25,
        sugarLevels: [0, 25, 50, 75, 100],
        iceOptions: ["Less Ice", "Normal", "Separate"],
        hasCoffee: true,
      ),
      Drinkitem(
        title: "Caramel Latte",
        description: "Espresso with caramel syrup.",
        img: "assets/drinks/ice/caramel_latte.png",
        sPrice: 3.00,
        lPrice: 3.50,
        sugarLevels: [0, 25, 50, 75, 100],
        iceOptions: ["Less Ice", "Normal", "Separate"],
        hasCoffee: true,
      ),
      Drinkitem(
        title: "Vanilla Latte",
        description: "Creamy vanilla flavored latte.",
        img: "assets/drinks/ice/vanilla_latte.png",
        sPrice: 3.00,
        lPrice: 3.50,
        sugarLevels: [0, 25, 50, 75, 100],
        iceOptions: ["Less Ice", "Normal", "Separate"],
        hasCoffee: true,
      ),
    ],
  ),

  Categorys(
    name: "Hot Coffee",
    items: [
      Drinkitem(
        title: "Espresso",
        description: "Strong espresso shot.",
        img: "assets/drinks/hot/espresso.png",
        sPrice: 1.80,
        lPrice: 2.20,
        sugarLevels: [0, 25, 50, 75, 100],
        iceOptions: [],
        hasCoffee: true,
      ),
      Drinkitem(
        title: "Cappuccino",
        description: "Espresso with steamed milk foam.",
        img: "assets/drinks/hot/cappuccino.png",
        sPrice: 2.80,
        lPrice: 3.30,
        sugarLevels: [0, 25, 50, 75, 100],
        iceOptions: [],
        hasCoffee: true,
      ),
      Drinkitem(
        title: "Flat White",
        description: "Smooth espresso with silky milk.",
        img: "assets/drinks/hot/flat_white.png",
        sPrice: 2.90,
        lPrice: 3.40,
        sugarLevels: [0, 25, 50, 75, 100],
        iceOptions: [],
        hasCoffee: true,
      ),
      Drinkitem(
        title: "Hot Latte", // Fixed: Replaced missing Mocha with hot_latte.png
        description: "Classic hot espresso with steamed milk.",
        img: "assets/drinks/hot/hot_latte.png",
        sPrice: 3.20,
        lPrice: 3.70,
        sugarLevels: [0, 25, 50, 75, 100],
        iceOptions: [],
        hasCoffee: true,
      ),
    ],
  ),

  Categorys(
    name: "Milk",
    items: [
      Drinkitem(
        title: "Chocolate Milk",
        description: "Fresh milk with chocolate.",
        img: "assets/drinks/milk/chocolate_milk.png",
        sPrice: 2.80,
        lPrice: 3.30,
        sugarLevels: [0, 25, 50, 75, 100],
        iceOptions: ["Less Ice", "Normal", "Separate"],
        hasCoffee: false,
      ),
      Drinkitem(
        title: "Strawberry Milk",
        description: "Fresh milk with strawberry syrup.",
        img: "assets/drinks/milk/strawberry_milk.png",
        sPrice: 2.90,
        lPrice: 3.40,
        sugarLevels: [0, 25, 50, 75, 100],
        iceOptions: ["Less Ice", "Normal", "Separate"],
        hasCoffee: false,
      ),
      Drinkitem(
        title: "Banana Milk",
        description: "Sweet banana flavored milk.",
        img: "assets/drinks/milk/banana_milk.png",
        sPrice: 3.00,
        lPrice: 3.50,
        sugarLevels: [0, 25, 50, 75, 100],
        iceOptions: ["Less Ice", "Normal", "Separate"],
        hasCoffee: false,
      ),
    ],
  ),

  Categorys(
    name: "Tea",
    items: [
      Drinkitem(
        title: "Coconut Matcha",
        description: "Premium matcha blended with fresh coconut milk.",
        img: "assets/drinks/teas/coconut_matcha.png",
        sPrice: 3.20,
        lPrice: 3.70,
        sugarLevels: [0, 25, 50, 75, 100],
        iceOptions: ["Less Ice", "Normal", "Separate"],
        hasCoffee: false,
      ),
      Drinkitem(
        title: "Matcha Latte",
        description: "Smooth Japanese matcha with fresh milk.",
        img: "assets/drinks/teas/matcha_latte.png",
        sPrice: 3.00,
        lPrice: 3.50,
        sugarLevels: [0, 25, 50, 75, 100],
        iceOptions: ["Less Ice", "Normal", "Separate"],
        hasCoffee: false,
      ),
      Drinkitem(
        title: "Tnaot Matcha",
        description: "Japanese matcha sweetened with Cambodian palm sugar.",
        img: "assets/drinks/teas/tnaot_matcha.png",
        sPrice: 3.30,
        lPrice: 3.80,
        sugarLevels: [0, 25, 50, 75, 100],
        iceOptions: ["Less Ice", "Normal", "Separate"],
        hasCoffee: false,
      ),
      Drinkitem(
        title: "Strawberry Matcha",
        description: "Layered strawberry puree with creamy matcha latte.",
        img: "assets/drinks/teas/strawberry_matcha.png",
        sPrice: 3.50,
        lPrice: 4.00,
        sugarLevels: [0, 25, 50, 75, 100],
        iceOptions: ["Less Ice", "Normal", "Separate"],
        hasCoffee: false,
      ),
    ],
  ),

  Categorys(
    name: "Frappe",
    items: [
      Drinkitem(
        title: "Mocha Frappe",
        description: "Blended mocha coffee.",
        img: "assets/drinks/frappe/mocha_frappe.png",
        sPrice: 3.80,
        lPrice: 4.30,
        sugarLevels: [0, 25, 50, 75, 100],
        iceOptions: [],
        hasCoffee: true,
      ),
      Drinkitem(
        title: "Matcha Avocado Frappe", 
        description: "Rich matcha blended with avocado.",
        img: "assets/drinks/frappe/matcha_avocado_frappe.png",
        sPrice: 4.30,
        lPrice: 4.80,
        sugarLevels: [0, 25, 50, 75, 100],
        iceOptions: [],
        hasCoffee: false,
      ),
      Drinkitem(
        title: "Cookies & Cream Frappe",
        description: "Creamy cookies blended with ice.",
        img: "assets/drinks/frappe/cookies_cream_frappe.png",
        sPrice: 4.20,
        lPrice: 4.70,
        sugarLevels: [0, 25, 50, 75, 100],
        iceOptions: [],
        hasCoffee: false,
      ),
      Drinkitem(
        title: "Matcha Frappe",
        description: "Blended matcha with milk.",
        img: "assets/drinks/frappe/matcha_frappe.png",
        sPrice: 4.10,
        lPrice: 4.60,
        sugarLevels: [0, 25, 50, 75, 100],
        iceOptions: [],
        hasCoffee: false,
      ),
    ],
  ),
];
